name: store_navigation_map
description: The map for the store navigation
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flame: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_compass: ^0.7.0
  flutter_local_notifications: ^13.0.0
  geolocator: ^9.0.2
  meta: ^1.8.0
  store_navigation_graph:
    git:
      url: https://github.com/ShoppingNavigation/navigation_graph.git
      ref: "29fefd62c88fe5fa551acfacdb6a9a8e40ec2d0c"
  store_shared_models:
    git:
      url: https://github.com/ShoppingNavigation/store_shared_models.git
      ref: "740c15d0bf3ad9de0327ea0e464dc3e16eef26f7"
  vibration: ^1.7.6
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
